"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables
env = environ.Env(
    DEBUG=(bool, True),
    USE_SUPABASE=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY must be set in environment, no default allowed
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-n4k#-0fqfa67+y*sbp+r2qnqpyaj!s1@0#ap^^$9lual^j5x9o",
)

# SECURITY: Fail if SECRET_KEY is default in production
if (
    not DEBUG
    and SECRET_KEY
    == "django-insecure-n4k#-0fqfa67+y*sbp+r2qnqpyaj!s1@0#ap^^$9lual^j5x9o"
):
    raise ValueError("SECRET_KEY must be set in production environment!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True)

# SECURITY: Strict ALLOWED_HOSTS - never allow '*' in production
if DEBUG:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
else:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
    if not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS:
        raise ValueError(
            "ALLOWED_HOSTS must be explicitly set and cannot contain '*' in production!"
        )


# Application definition

INSTALLED_APPS = [
    "daphne",  # ASGI server - must be first
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Third party
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # For token blacklisting
    "corsheaders",
    "channels",  # WebSocket support
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # dj-rest-auth
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # TrustFix apps
    "apps.core",
    "apps.users",
    "apps.services",
    "apps.technicians",
    "apps.bookings",
    "apps.payments",
    "apps.ai_engine",
    "apps.notifications",
]

MIDDLEWARE = [
    # Security first
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # Response compression
    "apps.core.middleware.SecurityHeadersMiddleware",
    "apps.core.middleware.MaintenanceModeMiddleware",
    "apps.core.shutdown.GracefulShutdownMiddleware",  # Graceful shutdown
    # CORS
    "corsheaders.middleware.CorsMiddleware",
    # Session/Auth
    "django.contrib.sessions.middleware.SessionMiddleware",
    "apps.core.middleware.JWTAuthMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    # Custom middleware
    "apps.core.middleware.RequestLoggingMiddleware",
    "apps.core.middleware.RateLimitMiddleware",
    "apps.core.middleware.UserActivityMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use Supabase PostgreSQL if USE_SUPABASE=True, otherwise use SQLite
if env.bool("USE_SUPABASE", default=False):
    # Supabase PostgreSQL Configuration
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("SUPABASE_DB_NAME"),
            "USER": env("SUPABASE_DB_USER"),
            "PASSWORD": env("SUPABASE_DB_PASSWORD"),
            "HOST": env("SUPABASE_DB_HOST"),
            "PORT": env("SUPABASE_DB_PORT", default="5432"),
            "CONN_MAX_AGE": 600,  # Connection pooling - 10 minutes
            "OPTIONS": {
                "sslmode": "require",
                "connect_timeout": 10,
                "options": "-c statement_timeout=30000",  # 30 seconds query timeout
            },
        }
    }
else:
    # Local SQLite Configuration (default for development)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "CONN_MAX_AGE": 600,  # Connection pooling
        }
    }

# Custom User Model
AUTH_USER_MODEL = "users.User"

# Site ID (required for allauth)
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth config (v2 style)
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

# allauth social account
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID", default=""),
            "secret": env("GOOGLE_CLIENT_SECRET", default=""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# Google OAuth (used by custom callback view)
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET", default="")
GOOGLE_REDIRECT_URI = env(
    "GOOGLE_REDIRECT_URI", default="http://localhost:3000/auth/callback"
)

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}

# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,  # Enable token blacklisting
    "AUTH_HEADER_TYPES": ("Bearer",),
    "UPDATE_LAST_LOGIN": True,
}

# TrustFix Business Configuration
VISITING_CHARGE_AMOUNT = 100  # ₹100 visiting charge
PLATFORM_FEE_PERCENT = 10  # 10% platform fee
MINIMUM_PLATFORM_FEE = 50  # Minimum ₹50 platform fee

# SMS Configuration
SMS_API_KEY = env("SMS_API_KEY", default="")
SMS_SENDER_ID = env("SMS_SENDER_ID", default="TRUSTX")

# AI Configuration
GROQ_API_KEY = env("GROQ_API_KEY", default="")
OPENAI_API_KEY = env("OPENAI_API_KEY", default="")

# FCM Push Notifications
FCM_SERVER_KEY = env("FCM_SERVER_KEY", default="")

# CORS - STRICT CONFIGURATION
# NEVER allow all origins in production
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
    # SECURITY: Fail if CORS not configured in production
    if not CORS_ALLOWED_ORIGINS:
        raise ValueError("CORS_ALLOWED_ORIGINS must be set in production!")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================
# Redis Cache Configuration
# ============================================

REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_CLASS": "redis.connection.BlockingConnectionPool",
            "CONNECTION_POOL_CLASS_KWARGS": {
                "max_connections": 50,
                "timeout": 20,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
        "KEY_PREFIX": "trustfix",
        "TIMEOUT": 300,  # 5 minutes default
    }
}

# Use Redis for session backend
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Cache time to live (in seconds)
CACHE_TTL = 60 * 15  # 15 minutes

# ============================================
# Django Channels Configuration
# ============================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 1500,  # Max messages in channel
            "expiry": 10,  # Message expiry in seconds
        },
    },
}


# ============================================
# Logging Configuration
# ============================================

from .logging_config import get_logging_config

LOGGING = get_logging_config(debug=DEBUG)

ADMINS = [
    ("TrustFix Admin", env("ADMIN_EMAIL", default="admin@trustfix.local")),
]


# ============================================
# Cookie Settings
# ============================================

# JWT Cookie settings
JWT_COOKIE_SECURE = not DEBUG  # HTTPS only in production
JWT_COOKIE_SAMESITE = "Lax"
JWT_COOKIE_HTTPONLY = True
JWT_COOKIE_MAX_AGE = 3600  # 1 hour

# CSRF Cookie
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = True

# Session Cookie
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 weeks


# ============================================
# Static files (CSS, JavaScript, Images)
# ============================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ============================================
# Default primary key field type
# ============================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================
# Feature Flags
# ============================================

FEATURE_FLAGS = {
    "ENABLE_AI_QUOTES": env.bool("ENABLE_AI_QUOTES", default=False),
    "ENABLE_REALTIME_TRACKING": env.bool("ENABLE_REALTIME_TRACKING", default=False),
    "ENABLE_WHATSAPP_NOTIFICATIONS": env.bool(
        "ENABLE_WHATSAPP_NOTIFICATIONS", default=False
    ),
    "ENABLE_REFERRAL_SYSTEM": env.bool("ENABLE_REFERRAL_SYSTEM", default=False),
}

# ============================================
# Maintenance Mode
# ============================================

MAINTENANCE_MODE = env.bool("MAINTENANCE_MODE", default=False)
